import {
  Sparkles,
  Pencil,
  ArrowRightLeft,
  UserCog,
  Phone,
  MessageCircle,
  Mail,
  StickyNote,
  Share2,
  CalendarPlus,
  CheckCircle2,
  MapPin,
  ClipboardCheck,
  Handshake,
  GitBranch,
  Trophy,
  Coins,
  Flame,
} from "lucide-react";

type Meta = { icon: React.ComponentType<{ className?: string }>; bg: string; fg: string; label: string };

export const ACTIVITY_META: Record<string, Meta> = {
  LEAD_CREATED: { icon: Sparkles, bg: "bg-brand-100", fg: "text-brand-700", label: "Lead created" },
  LEAD_UPDATED: { icon: Pencil, bg: "bg-ink-100", fg: "text-ink-600", label: "Lead updated" },
  STATUS_CHANGED: { icon: ArrowRightLeft, bg: "bg-blue-100", fg: "text-blue-700", label: "Status changed" },
  TEMPERATURE_CHANGED: { icon: Flame, bg: "bg-red-100", fg: "text-red-600", label: "Temperature changed" },
  ASSIGNED: { icon: UserCog, bg: "bg-violet-100", fg: "text-violet-700", label: "Assigned" },
  CALL: { icon: Phone, bg: "bg-emerald-100", fg: "text-emerald-700", label: "Call" },
  WHATSAPP: { icon: MessageCircle, bg: "bg-green-100", fg: "text-green-700", label: "WhatsApp" },
  EMAIL: { icon: Mail, bg: "bg-blue-100", fg: "text-blue-700", label: "Email" },
  NOTE: { icon: StickyNote, bg: "bg-amber-100", fg: "text-amber-700", label: "Note" },
  PROPERTY_SHARED: { icon: Share2, bg: "bg-brand-100", fg: "text-brand-700", label: "Property shared" },
  FOLLOWUP_CREATED: { icon: CalendarPlus, bg: "bg-ink-100", fg: "text-ink-600", label: "Follow-up scheduled" },
  FOLLOWUP_COMPLETED: { icon: CheckCircle2, bg: "bg-emerald-100", fg: "text-emerald-700", label: "Follow-up completed" },
  SITE_VISIT_SCHEDULED: { icon: MapPin, bg: "bg-blue-100", fg: "text-blue-700", label: "Site visit scheduled" },
  SITE_VISIT_COMPLETED: { icon: MapPin, bg: "bg-emerald-100", fg: "text-emerald-700", label: "Site visit completed" },
  SITE_VISIT_FEEDBACK: { icon: ClipboardCheck, bg: "bg-violet-100", fg: "text-violet-700", label: "Visit feedback" },
  DEAL_CREATED: { icon: Handshake, bg: "bg-gold-100", fg: "text-gold-600", label: "Deal created" },
  DEAL_STAGE_CHANGED: { icon: GitBranch, bg: "bg-blue-100", fg: "text-blue-700", label: "Deal stage changed" },
  DEAL_CLOSED: { icon: Trophy, bg: "bg-emerald-100", fg: "text-emerald-700", label: "Deal closed" },
  COMMISSION_UPDATED: { icon: Coins, bg: "bg-gold-100", fg: "text-gold-600", label: "Commission updated" },
};
